Upgrade to make compatible with JupyterLab 3
jupyterlab/jupyterlab-telemetry pull request #24
Opened 2022-03-16 02:01 UTC by 3coins

Fixes #23

2022-03-16 10:08 UTC, fcollonval commented
Thanks @3coins 

It will be good to add some testing for this one - at least the default linter/packaging/installation available from the cookiecutter. The best would of course be to have some tests that demonstrate its usage.

2022-03-16 15:59 UTC, 3coins commented
> Thanks @3coins
> 
> It will be good to add some testing for this one - at least the default linter/packaging/installation available from the cookiecutter. The best would of course be to have some tests that demonstrate its usage.

Will do. Thanks.

2022-03-17 02:50 UTC, blink1073 commented
Kicking now that actions are working again

2022-03-17 02:51 UTC, blink1073 commented
Ah, they'll only run in your fork until we merge.

2022-03-17 11:18 UTC, fcollonval commented
@3coins it seems you have a syntax error in the workflow file: https://github.com/3coins/jupyterlab-telemetry/actions/runs/1994732900/workflow

2022-03-17 20:34 UTC, blink1073 commented
@3coins you accidentally checked in the `coverage` directory.

2022-03-17 22:46 UTC, 3coins commented
@fcollonval @blink1073 
Thanks for catching the workflow error. I am still working on the tests, will correct this error shortly.

2022-03-18 18:15 UTC, 3coins commented
@Zsailer
I am not able to get the python tests to pass, event though I can verify that the server extension is installed and tested that the endpoint works in jupyterlab, when I run pytest, it is returning a 404.
```
==================================================================== FAILURES =====================================================================
____________________________________________________________________ test_put _____________________________________________________________________

jp_fetch = <function jp_fetch.<locals>.client_fetch at 0x7faba2c279d0>

    async def test_put(jp_fetch):
>       r = await jp_fetch(
                    'telemetry',
                    method='PUT',
                    body=json.dumps({
                        'foo': 'bar'
                    })
                )
E       tornado.httpclient.HTTPClientError: HTTP 404: Not Found

jupyterlab_telemetry/tests/test_handlers.py:6: HTTPClientError
-------------------------------------------------------------- Captured stderr setup --------------------------------------------------------------
[D 2022-03-18 10:45:39.163 ServerApp] Config changed: {'ServerApp': {'jpserver_extensions': {'jupyter_telemetry': True}}, 'NotebookNotary': {'db_file': ':memory:'}}
The module 'jupyter_telemetry' could not be found. Are you sure the extension is installed?

WARNING  ServerApp:log.py:59 404 PUT /a%40b/telemetry (127.0.0.1) 25.35ms referer=None
============================================================= short test summary info =============================================================
FAILED jupyterlab_telemetry/tests/test_handlers.py::test_put - tornado.httpclient.HTTPClientError: HTTP 404: Not Found
```

Here is the server extension list showing that the extension is enabled.

```
± |jlab-3-upgrade U:1 ✗| → jupyter server extension list
Config dir: /Users/pijain/.jupyter

Config dir: /Users/pijain/opt/anaconda3/envs/jlab-3.x-telemetry/etc/jupyter
    jupyterlab_telemetry enabled
    - Validating jupyterlab_telemetry...
      jupyterlab_telemetry 1.0.0 OK
```
I have committed all the changes, but marked the test to skip.

2022-03-18 20:35 UTC, 3coins commented
Fixed the python tests in the latest commit.

2022-03-19 09:07 UTC, fcollonval requested changes
Thanks @3coins (especially for adding the tests)

I have a minor change as the main branch is called `master` on this repository.

Otherwise we should merge and iterate from there - in particular if the CI fails.

2022-03-19 09:07 UTC, fcollonval commented on .github/workflows/build.yml
> +    branches: main
```suggestion
    branches: master
```

2022-03-19 09:07 UTC, fcollonval commented on .github/workflows/check-release.yml
> +      - main
```suggestion
      - master
```

2022-03-19 09:07 UTC, fcollonval commented on .github/workflows/check-release.yml
> +      - main
```suggestion
      - master
```

2022-03-19 10:57 UTC, merged

2022-03-19 11:05 UTC, blink1073 commented
Indeed both workflows failed

2022-03-19 18:24 UTC, 3coins commented
> Indeed both workflows failed

Oh no, let me take a look.